In [32]:
#Step 1: Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as mtp 



In [33]:
#Step 2: Load the Dataset
data_set = pd.read_csv('drug200.csv')
# Display the first few rows of the dataset
data_set.head()

Age  BP  Cholesterol  Na_to_K   Drug
0   23   1            1   25.355  drugY
1   47   0            1   13.093  drugC
2   47   0            1   10.114  drugC
3   28   2            1    7.798  drugX
4   61   0            1   18.043  drugY

In [34]:

x= data_set.iloc[:, [0,1,2,3]].values  
y= data_set.iloc[:, 4].values  
print(x)
print(y)

[[23.     1.     1.    25.355]
 [47.     0.     1.    13.093]
 [47.     0.     1.    10.114]
 [28.     2.     1.     7.798]
 [61.     0.     1.    18.043]
 [22.     2.     1.     8.607]
 [49.     2.     1.    16.275]
 [41.     0.     1.    11.037]
 [60.     2.     1.    15.171]
 [43.     0.     2.    19.368]
 [47.     0.     1.    11.767]
 [34.     1.     2.    19.199]
 [43.     0.     1.    15.376]
 [74.     0.     1.    20.942]
 [50.     2.     1.    12.703]
 [16.     1.     2.    15.516]
 [69.     0.     2.    11.455]
 [43.     1.     1.    13.972]
 [23.     0.     1.     7.298]
 [32.     1.     2.    25.974]
 [57.     0.     2.    19.128]
 [63.     2.     1.    25.917]
 [47.     0.     2.    30.568]
 [48.     0.     1.    15.036]
 [33.     0.     1.    33.486]
 [28.     1.     2.    18.809]
 [31.     1.     1.    30.366]
 [49.     2.     2.     9.381]
 [39.     0.     2.    22.697]
 [45.     0.     1.    17.951]
 [18.     2.     2.     8.75 ]
 [74.     1.     1.     9.567]
 [49.   

In [35]:
#Step 3: Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  

In [36]:
#Step 4: Feature Scaling
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()  
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)

In [37]:
#Step 5:#Train the model 
#Fitting K-NN classifier to the training set  

from sklearn.neighbors import KNeighborsClassifier  
classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier.fit(x_train, y_train)  

KNeighborsClassifier()

In [38]:
#Step 6: Evaluate the Model
#Predicting the test set result  
y_pred= classifier.predict(x_test)  

In [39]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  


In [40]:
cm

array([[ 4,  1,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0, 16,  0],
       [ 1,  2,  0,  2, 20]], dtype=int64)

In [31]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("KNN Algorithm accuracy: ", metrics.accuracy_score(y_test,y_pred))

KNN Algorithm accuracy:  0.88
